# Hotel Booking Assignment 

**Instructions:** Load the dataset first and write your own solution in each empty code cell.

In [1]:
# Load the required libraries and dataset here
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("hotel_bookings.csv")
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07


## Part A – NumPy (5 Questions)

### Q1. Numeric columns ko NumPy array me convert karo.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

In [5]:
round(df.describe(), 2).T

,count,mean,std,min,25%,50%,75%,max
is_canceled,119390.0,0.37,0.48,0.00,0.00,0.00,1.0,1.0
lead_time,119390.0,104.01,106.86,0.00,18.00,69.00,160.0,737.0
arrival_date_year,119390.0,2016.16,0.71,2015.00,2016.00,2016.00,2017.0,2017.0
arrival_date_week_number,119390.0,27.17,13.61,1.00,16.00,28.00,38.0,53.0
arrival_date_day_of_month,119390.0,15.80,8.78,1.00,8.00,16.00,23.0,31.0
stays_in_weekend_nights,119390.0,0.93,1.00,0.00,0.00,1.00,2.0,19.0
stays_in_week_nights,119390.0,2.50,1.91,0.00,1.00,2.00,3.0,50.0
adults,119390.0,1.86,0.58,0.00,2.00,2.00,2.0,55.0
children,119386.0,0.10,0.40,0.00,0.00,0.00,0.0,10.0
babies,119390.0,0.01,0.10,0.00,0.00,0.00,0.0,10.0


In [6]:
numeric_df = df.select_dtypes(include=[np.number])
numeric_array = numeric_df.to_numpy()

print(numeric_array.shape)
print(numeric_array)

(119390, 20)
[[0.0000e+00 3.4200e+02 2.0150e+03 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 7.3700e+02 2.0150e+03 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 7.0000e+00 2.0150e+03 ... 7.5000e+01 0.0000e+00 0.0000e+00]
 ...
 [0.0000e+00 3.4000e+01 2.0170e+03 ... 1.5771e+02 0.0000e+00 4.0000e+00]
 [0.0000e+00 1.0900e+02 2.0170e+03 ... 1.0440e+02 0.0000e+00 0.0000e+00]
 [0.0000e+00 2.0500e+02 2.0170e+03 ... 1.5120e+02 0.0000e+00 2.0000e+00]]


### Q2. Sabhi numeric columns ka mean NumPy se nikalo.

### Q3. Sabhi numeric columns ka maximum aur minimum value nikalo.

### Q4. `adr` column ka median NumPy se nikalo.

### Q5. `lead_time` ka standard deviation NumPy se nikalo.

## Part B – Pandas Basics (15 Questions)

### Q1. Dataset load karo.

### Q2. First 10 rows display karo.

### Q3. Last 10 rows display karo.

### Q4. Shape print karo.

### Q5. Columns ke naam print karo.

### Q6. Dataset ki information nikalo.

### Q7. Summary statistics nikalo.

### Q8. Missing values count karo.

### Q9. Missing values percentage nikalo.

### Q10. Duplicate rows check karo.

### Q11. Duplicate rows remove karo.

### Q12. Total missing values remove ya fill karo (appropriate method choose karo).

### Q13. Datatypes check karo.

### Q14. Kitne object columns hain?

### Q15. Kitne numeric columns hain?

## Part C – Data Cleaning (10 Questions)

### Q1. `children` aur `country` column ke missing values handle karo.

### Q2. Jis column me 90% se zyada missing values ho uska analysis karo (drop karna chahiye ya nahi?).

### Q3. Object columns ke unique values nikalo.

### Q4. `reservation_status_date` ko datetime me convert karo.

### Q5. `hotel` column me kitni unique categories hain?

### Q6. `meal` column ki frequency nikalo.

### Q7. `market_segment` ke unique values nikalo.

### Q8. `distribution_channel` ki frequency nikalo.

### Q9. `reserved_room_type` aur `assigned_room_type` compare karo.

### Q10. `is_canceled` ka distribution nikalo.

## Part D – Data Analysis (15 Questions)

### Q1. Kis hotel me sabse zyada bookings hui?

### Q2. Cancelled bookings kitni hain?

### Q3. Country-wise top 10 bookings.

### Q4. Average ADR hotel-wise.

### Q5. Average lead time.

### Q6. Kis month me sabse zyada bookings hui?

### Q7. Meal type distribution.

### Q8. Market segment-wise booking count.

### Q9. Deposit type analysis.

### Q10. Repeat guests kitne hain?

### Q11. Average stay weekend vs weekday.

### Q12. Adults, children aur babies ka average nikalo.

### Q13. Room upgrade kitni baar hua?

### Q14. Reservation status analysis.

### Q15. Top 10 countries by booking.

## Part E – Matplotlib (8 Questions)

### Q1. Hotel-wise booking bar chart.

### Q2. Booking cancellation pie chart.

### Q3. ADR histogram.

### Q4. Monthly booking line chart.

### Q5. Lead time histogram.

### Q6. Adults vs ADR scatter plot.

### Q7. Weekend nights box plot.

### Q8. Meal distribution horizontal bar chart.

## Part F – Seaborn (12 Questions)

### Q1. Hotel countplot.

### Q2. Market segment countplot.

### Q3. Boxplot of ADR by hotel.

### Q4. Boxplot of lead time by cancellation.

### Q5. Violin plot of ADR.

### Q6. Pairplot of important numeric columns.

### Q7. Heatmap of correlation matrix.

### Q8. Histogram + KDE of ADR.

### Q9. Scatterplot of lead time vs ADR.

### Q10. Barplot of average ADR by meal.

### Q11. Countplot of reservation status.

### Q12. Stripplot of ADR by hotel.